### ISSUE TITLE
MultiPolygon coverage

### ISSUE THREAD

**Issue by veltman** [Turfjs/turf-intersect#13]
Is there any interest in a pull request that would allow for MultiPolygons as input/output?  I'd guess a lot of people are writing the same "loop through the input polygons, loop through the comparison polygons, combine all the shards of overlap" code.

It's not super-complicated to wrap this with that extra code but it seems like it would make sense to include it here unless there's a design reason I'm missing for limiting it to polygons.

**Comment by tcql** [comment]
@veltman thanks for the interest in contributing. we're working on a rewrite of the turf-intersect, turf-union, and turf-difference internals, which will take care of this. This is still a little ways off, so if you had a need for multipolygon support in the near future, go ahead and write the wrapping :)

**Comment by franckl** [comment]
hi @tcql , is your team still working on a rewrite ?

**Comment by valentinbdv** [comment]
Hi @tcql, awesome library but I am missing this improvement too!

**Comment by mykhas** [comment]
Hi @tcql, I also need this improvement. Could I work on PR to fix this one?

**Comment by DenisCarriere** [comment]
MultiPolygon support has been added to `@turf/intersect`, please re-open this issue if there are other specific modules that are missing MultiPolygon support.
