### ISSUE TITLE
About turf-intersect properties

### ISSUE THREAD

**Issue by guangguang00** [Turfjs/turf-intersect#19]
how can I get the  properties from the intersect which come from poly1 and poly2

**Comment by DenisCarriere** [comment]
Ideally you would do your `intersect` operation on your polygons one by one, there isn't a way to extract the properties which intersects using the `@turf/intersect` module.

**Comment by kanaujiasachin** [comment]
I had the same question for Line Intersect
https://turfjs.org/docs/#lineIntersect

You can have a feature collection and it would be quite useful to find the properties of the source which is getting intersected.
