### ISSUE TITLE
remove jsts

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-intersect#2]
probably will need to implement this:

http://en.wikipedia.org/wiki/Weiler%E2%80%93Atherton_clipping_algorithm

**Comment by donpark** [comment]
Take a look at [JsClipper](http://jsclipper.sourceforge.net) which implements Vatti's clipping algorithm which is supposedly more general. Latest version is 94K unminified which seems reasonable. FYI, SourceForge repo has later version than Github repo.

**Comment by donpark** [comment]
nvm. just read your comments and realized you're already aware of JsClipper.

**Comment by tmcw** [comment]
-> https://github.com/Turfjs/turf/issues/88
