### ISSUE TITLE
Add expected responses to docs

### ISSUE THREAD

**Issue by lyzidiamond** [Turfjs/turf-intersect#6]
`undefined` => no intersect
Polygon => overlap
MultiLineString => share a border

**Comment by tmcw** [comment]
docs for this in jsdoc: http://usejsdoc.org/tags-param.html#multiple-types-and-repeatable-parameters

**Comment by lyzidiamond** [comment]
This is done via https://github.com/Turfjs/turf-intersect/commit/1f82271bc037635c4adbf8156e6817e8f321f647. Closing.
